pipeline:
  name: Sandbox
  identifier: Sandbox
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - parallel:
        - stage:
            name: Build Go
            identifier: Build_1
            description: ""
            type: CI
            spec:
              cloneCodebase: false
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - parallel:
                      - step:
                          type: Run
                          name: Hello
                          identifier: Hello
                          spec:
                            shell: Sh
                            command: echo "hello world"
                      - step:
                          type: Run
                          name: Another Hello
                          identifier: Another_Hello
                          spec:
                            shell: Sh
                            command: echo "ave mundus"
              caching:
                enabled: false
                paths: []
        - stage:
            name: Build Rust
            identifier: Build_Rust
            description: ""
            type: CI
            spec:
              cloneCodebase: false
              platform:
                os: Windows
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - parallel:
                      - step:
                          type: Run
                          name: Hi
                          identifier: Hi
                          spec:
                            shell: Sh
                            command: echo "Hello!"
                      - step:
                          type: Run
                          name: Oh hello
                          identifier: Oh_hello
                          spec:
                            shell: Powershell
                            command: "'Hello, World!' | Write-Host"
    - stage:
        name: Envars
        identifier: Envars
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Print Metadata
                  identifier: Print_Metadata
                  spec:
                    shell: Sh
                    command: |-
                      echo <+pipeline.name>             # Output example: My_Pipeline_Name
                      echo <+pipeline.executionId>      # Output example: 1234-5678-abcd
                      echo <+pipeline.sequenceId>       # Output example: 16
                      echo <+pipeline.status>           # Output example: SUCCESS
                      echo <+pipeline.triggeredBy.name> # Output example: john.doe@example.com
                      echo <+project.name>              # Output example: My_Project_Name
                      echo <+org.name>                  # Output example: My_Organization_Name
  notificationRules:
    - name: Webhook
      identifier: Webhook
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Webhook
        spec:
          webhookUrl: https://hooks.slack.com/services/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
      enabled: true
    - name: Pipeline Level Slack Notification
      identifier: Pipeline_Level_Slack_Notification
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Slack
        spec:
          userGroups: []
          webhookUrl: https://hooks.slack.com/services/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
      enabled: true
