pipeline:
  name: Sandbox
  identifier: Sandbox
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build 1
        identifier: Build_1
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - parallel:
                  - step:
                      type: Run
                      name: Hello
                      identifier: Hello
                      spec:
                        shell: Sh
                        command: echo "hello world"
                  - step:
                      type: Run
                      name: Another Hello
                      identifier: Another_Hello
                      spec:
                        shell: Sh
                        command: echo "ave mundus"
