pipeline:
  name: Sandbox
  identifier: Sandbox
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - parallel:
        - stage:
            name: Build Go
            identifier: Build_1
            description: ""
            type: CI
            spec:
              cloneCodebase: false
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - parallel:
                      - step:
                          type: Run
                          name: Hello
                          identifier: Hello
                          spec:
                            shell: Sh
                            command: echo "hello world"
                      - step:
                          type: Run
                          name: Another Hello
                          identifier: Another_Hello
                          spec:
                            shell: Sh
                            command: echo "ave mundus"
              caching:
                enabled: false
                paths: []
        - stage:
            name: Build Rust
            identifier: Build_Rust
            description: ""
            type: CI
            spec:
              cloneCodebase: false
              platform:
                os: Windows
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - parallel:
                      - step:
                          type: Run
                          name: Hi
                          identifier: Hi
                          spec:
                            shell: Sh
                            command: exit 137
                      - step:
                          type: Run
                          name: Oh hello
                          identifier: Oh_hello
                          spec:
                            shell: Powershell
                            command: "'Hello, World!' | Write-Host"
    - stage:
        name: post deployment check
        identifier: post_deployment_check
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Http
                  name: Post deployment check
                  identifier: Post_deployment_check
                  spec:
                    url: https://httpbin.org/get
                    method: GET
                    headers: []
                    inputVariables: []
                    outputVariables: []
                  timeout: 1m
        tags: {}
  notificationRules:
    - name: Webhook
      identifier: Webhook
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Webhook
        spec:
          webhookUrl: https://hooks.slack.com/services/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
      enabled: true
    - name: Pipeline Level Slack Notification
      identifier: Pipeline_Level_Slack_Notification
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Slack
        spec:
          userGroups: []
          webhookUrl: https://hooks.slack.com/services/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
      enabled: true
